project:
  type: book
  output-dir: docs

book:
  sidebar: 
    logo: images/logo-team-full-color.svg
  chapters:
    - index.qmd
    
    - part: Overview and Setup
      chapters: 
        - workshop-access.qmd
        - posit-team-overview.qmd
        - user-configuration.qmd
    - part: Data
      chapters: 
        - data.qmd
        - exercise-ETL.qmd
    - part: Understand
      chapters: 
        - modeling.qmd
        - exercise-model.qmd
    - part: Communicate
      chapters: 
        - shiny.qmd
        - exercise-shiny-py.qmd
        - exercise-shiny-r.qmd
    - part: Bonus Content
      chapters: 
        - bonus-content.qmd


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

